spring:
  application:
    name: rest-api-demo

  sql:
    init:
      data-locations: classpath:sql/data.sql

  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true