spring:
  application:
    name: next-course-chat-service
  data:
    redis:
      port: 6379
      host: 127.0.0.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true
    fetchRegistry: true

grpc:
  server:
    port: 9006

server:
  port: 8006