spring:
  application:
    name: next-playback-service

  datasource:
    url: jdbc:mysql://localhost:3306/next_playback?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: fast
    password: campus

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema-mysql.sql
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true
    fetchRegistry: true