apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-gateway
  labels:
    app: next-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: next-gateway
  template:
    metadata:
      labels:
        app: next-gateway
    spec:
      containers:
        - name: next-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
