graph LR;
    subgraph "Service Discovery"
        sd((Discovery Service))
    end
    subgraph "Mobile API Gateway"
        gw((Router))
        rl((Rate Limiter))
        sec((Spring Security))
    end
    subgraph "Web API Gateway"
        gw-web((Router))
        rl-web((Rate Limiter))
        sec-web((Spring Security))
    end
    subgraph "book-api"
        book["Book API"]
    end
    subgraph "payment-api"
        payment["Payment API"]
    end

    sd --> book
    sd --> payment
    gw --> sec
    gw --> rl
    gw --> sd
    gw-web --> sec-web
    gw-web --> rl-web
    gw-web --> sd
    rl --> sec
    rl-web --> sec-web
    sec --> book
    sec-web --> book
    sec --> payment
    sec-web --> payment
