graph LR;
    subgraph "API Gateway"
        gw((Router))
    end
    subgraph "Service Discovery"
        sd((Discovery Service))
    end
    subgraph "book-api"
        book["Book API"]
    end
    subgraph "payment-api"
        payment["Payment API"]
    end

    gw --> sd
    sd <--> book
    sd <--> payment
