### 로그인
POST http://localhost:8001/login
Content-Type: application/json

{
  "username": "fast",
  "password": "campus"
}

> {% client.global.set("authToken", response.body.token); %}

### 책 정보 조회
GET http://localhost:8001/books/3
Authorization: Bearer {{authToken}}