apiVersion: v1
kind: Service
metadata:
  name: next-user-service
  labels:
    app: next-user-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: next-user-service
