apiVersion: v1
kind: Service
metadata:
  name: next-playback-service
  labels:
    app: next-playback-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: 8080
      protocol: TCP
      name: grpc
  selector:
    app: next-playback-service
